### ISSUE TITLE
Sample Connector:MySql is failing due to missing DB table

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/Samples#129]
## Describe the bug
Sample Connector...MySql is failing. It appears database is not being initialized correctly.

From the sample app's data page:
`MySqlException: Table 'service_instance_db.TestData' doesn't exist` 

## Steps to reproduce 
Assuming CF instance: `apps.pcfone.io`
1. cd `Connectors\src\AspDotNetCore\MySql`
2. run `cf create-service p.mysql db-small myMySqlService`
3. run `dotnet publish -f netcoreapp2.1 -r ubuntu.16.04-x64`
4.  run `cf push -f manifest.yml -p bin/Debug/netcoreapp2.1/ubuntu.16.04-x64/publish -n sampleissue`
5. goto https://sampleissue.apps.pcfone.io/Home/MySqlData

## Expected behavior
Working sample returns a page containing `Key 1 = Row1 Text`

## Environment
- Sample name: MySql Connector
- Platform: Cloud Foundry
- .NET Version: .NET Core 2.1, 3.1
- Steeltoe Version: 2.4.0
- Branch: 2.x

**Comment by ccheetham** [comment]
Sample log:
```
2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'service_instance_db.TestData' doesn't exist
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at MySql.Controllers.HomeController.MySqlData(MySqlConnection dbConnection) in /Users/ccheetham/src/SteeltoeOSS/Samples/Connectors/src/AspDotNetCore/MySql/Controllers/HomeController.cs:line 21
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at lambda_method(Closure , Object , Object[] )
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT --- End of stack trace from previous location where exception was thrown ---
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT --- End of stack trace from previous location where exception was thrown ---
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   2020-04-07T13:34:53.48-0400 [APP/PROC/WEB/0] OUT    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by ccheetham** [comment]
No longer failing
