### ISSUE TITLE
Hystrix Dashboard can't connect to Fortune-Teller-UI

### ISSUE THREAD

**Issue by Julian-Chu** [SteeltoeOSS/Samples#32]
Hello all,

I followed the document to run circuit breaker sample. When I input the url http://localhost:5555/hystrix/hystrix.steeam and click Monitor Stream, the dashboard show "Unable to connect to Command Metric Stream."

![day21_2](https://user-images.githubusercontent.com/7224544/34728338-edf35bda-f559-11e7-9ea3-5c6444445fc1.png)

some messages show in the log

in Fortune-Teller-UI:
- error about RabbitMQ
```
fail: Steeltoe.CircuitBreaker.Hystrix.MetricsStream.HystrixMetricsStreamPublisher[0]
      Error sending metrics to Hystrix dashboard, metrics streaming disabled: RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=404, text="NOT_FOUND - no exchange 'spring.cloud.hystrix.stream' in vhost '/'", classId=60, methodId=40, cause=
         at RabbitMQ.Client.Impl.SessionBase.Transmit(Command cmd)
         at RabbitMQ.Client.Impl.ModelBase.ModelSend(MethodBase method, ContentHeaderBase header, Byte[] body)
         at RabbitMQ.Client.Impl.ModelBase.BasicPublish(String exchange, String routingKey, Boolean mandatory, IBasicProperties basicProperties, Byte[] body)
         at Steeltoe.CircuitBreaker.Hystrix.MetricsStream.HystrixMetricsStreamPublisher.<StartMetricsPublishing>b__11_0(List`1 jsonList)
```
- 404: Endpoint is not founded
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5555/hystrix/hystrix.stream
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 253.0019ms 404
```
In Hystrix Dashboard log
```
Proxy opening connection to: http://localhost:5555/hystrix/hystrix.stream

2018-01-09 16:10:03.667  WARN 22780 --- [nio-7979-exec-3] ashboardConfiguration$ProxyStreamServlet : Failed opening connection to http://localhost:5555/hystrix/hystrix.stream : 404 : HTTP/1.1 404 Not Found
2018-01-09 16:10:03.667  WARN 22780 --- [nio-7979-exec-2] ashboardConfiguration$ProxyStreamServlet : Failed opening connection to http://localhost:5555/hystrix/hystrix.stream : 404 : HTTP/1.1 404 Not Found
```

It seems dashboard can't find  endpoint in the Fortune-Teller-UI.
How could I solve it?

Thanks!

**Comment by TimHess** [comment]
Hi @Julian-Chu, 
For running with the Hytrix dashboard locally, be sure to Set the BUILD environment variable to LOCAL (i.e. `SET BUILD=LOCAL`, `BUILD=LOCAL` or `export BUILD=LOCAL`)

Please note that you'll want to reset the BUILD variable before pushing to Cloud Foundry (ie `SET BUILD=` or `unset BUILD`)

**Comment by Julian-Chu** [comment]
Hi @TimHess ,

Thanks for quick reply. You save my time!
Just another situation(not issue),  when I run 
"dotnet run -f netcoreapp2.0 --server.urls http://*:5555" without set BUILD=LOCAL --> 
shut-down with ctrl+c --> 
SET BUILD=LOCAL -->
"dotnet run -f netcoreapp2.0 --server.urls http://*:5555"

It seems some resources are not released in this situation , then I have to close the this console and start new console.  please see the following for reference

```
C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI (master -> origin)
λ SET BUILD=LOCAL

C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI (master -> origin)
λ dotnet run -f netcoreapp2.0 --server.urls http://*:5555
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj...
  Restore completed in 2.03 sec for C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj.
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll' because it is being used by another process.  [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". Beginning retry 2 in 1000ms. The process cannot access the file 'C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll' because it is being used by another process.  [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". Beginning retry 3 in 1000ms. The process cannot access the file 'C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll' because it is being used by another process.  [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". Beginning retry 4 in 1000ms. The process cannot access the file 'C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll' because it is being used by another process.  [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". Beginning retry 5 in 1000ms. The process cannot access the file 'C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll' because it is being used by another process.  [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". Beginning retry 6 in 1000ms. The process cannot access the file 'C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll' because it is being used by another process.  [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". Beginning retry 7 in 1000ms. The process cannot access the file 'C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll' because it is being used by another process.  [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". Beginning retry 8 in 1000ms. The process cannot access the file 'C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll' because it is being used by another process.  [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". Beginning retry 9 in 1000ms. The process cannot access the file 'C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll' because it is being used by another process.  [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". Beginning retry 10 in 1000ms. The process cannot access the file 'C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll' because it is being used by another process.  [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): error MSB3027: Could not copy "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". Exceeded retry count of 10. Failed.  [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]
C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets(4106,5): error MSB3021: Unable to copy file "obj\Debug\netcoreapp2.0\Fortune-Teller-UI.dll" to "bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll". The process cannot access the file 'C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\bin\Debug\netcoreapp2.0\Fortune-Teller-UI.dll' because it is being used by another process. [C:\Users\yulan\Documents\Visual Studio 2017\Projects\Samples\CircuitBreaker\src\AspDotNetCore\FortuneTeller\Fortune-Teller-UI\Fortune-Teller-UI.csproj]

The build failed. Please fix the build errors and run again.
```

**Comment by yuezhongxin** [comment]
Hi, @TimHess ,
Fortune-Teller-UI4 has the same error(GET http://localhost:5000/hystrix/hystrix.stream 404), Fortune-Teller-UI4 built for ASP.NET 4.x.

How can I solve it, thanks!

**Comment by TimHess** [comment]
Hi @yuezhongxin,
The ASP.NET 4x Circuit Breaker sample was not built to run outside of Cloud Foundry. If you do not have Cloud Foundry available, it will take a fair bit of effort to get the Hystrix Dashboard working as we don't currently have a nuget package that provides the endpoints for making it work on 4x.

You can see what went into making that work on ASP.NET Core here: https://github.com/SteeltoeOSS/CircuitBreaker/tree/dev/src/Steeltoe.CircuitBreaker.Hystrix.MetricsEventsCore or you can follow the story for adding the functionality here: https://www.pivotaltracker.com/story/show/157806758 - but please note that I just now added the story to the backlog, so it hasn't been researched, estimated or prioritized.

**Comment by ravichigurupalli** [comment]
Hi All,

I am facing below issue when i am debugging in local .net core 2.1 application and it is going to fallback method. Few days back these hytrx commands are working perfectly don't have any changes in configuration side. 
And i am using Steeltoe.CircuitBreaker.Hystrix.MetricsStreamCore and Steeltoe.CircuitBreaker.HystrixCore are 2.1.1 version. Please help me.

Steeltoe.CircuitBreaker.Hystrix.MetricsStream.RabbitMetricsStreamPublisher:Error: Error creating connection/channel, metrics streaming disabled: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=530, text="NOT_ALLOWED - vhost / not found", classId=10, methodId=40, cause=
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ConnectionOpen(String virtualHost, String capabilities, Boolean insist)
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at Steeltoe.CircuitBreaker.Hystrix.MetricsStream.RabbitMetricsStreamPublisher.EnsureConnection()
The thread 0x2c94 has exited with code 0 (0x0).
Exception thrown: 'System.NullReferenceException' in Dell.Product.TransformLayer.Services.dll
Steeltoe.CircuitBreaker.Hystrix.MetricsStream.RabbitMetricsStreamPublisher:Debug: Discarding Hystrix Metrics, no connection
