### ISSUE TITLE
DiscoveryClient example won't start on a Mac

### ISSUE THREAD

**Issue by vijayvepa** [SteeltoeOSS/Samples#34]
Getting this error on startup:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. (Device not configured) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Device not configured
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Steeltoe.Discovery.Eureka.EurekaInstanceConfig.GetHostAddress(Boolean refresh)
   at Steeltoe.Discovery.Eureka.EurekaInstanceConfig..ctor()
```

I did the investigation and tracked it down to https://github.com/dotnet/corefx/issues/13309 . 

**Workaround**
Get current hostname and add it to the `/etc/hosts` file. 
Posted an issue here to check if this call can be removed from eureka client.

**Comment by dtillman** [comment]
Closing this .. please reopen if the changes don't help!
